### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [PKU-MARL/Model-Based-MARL#3]
Hello.
Thank you for your worthwhile materials!
Following your instructions, I only install sumo version 1.14.1
My errors when running

(Py) osboxes@osboxes:~/Desktop/Model-Based-MARL$ python launcher.py --env ENV --algo ALGO --name NAME --para PARA
/home/osboxes/Desktop/Model-Based-MARL/algorithms/envs/flow/core/kernel/__init__.py:10: PendingDeprecationWarning: flow.core.kernel.scenario will be deprecated in a future release. Please use flow.core.kernel.network instead.
  PendingDeprecationWarning
Traceback (most recent call last):
  File "launcher.py", line 197, in <module>
    input_args = parse_args()
  File "launcher.py", line 187, in parse_args
    args.para = json.loads(args.para.replace('\'', '\"'))
  File "/home/osboxes/anaconda3/envs/Py/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/osboxes/anaconda3/envs/Py/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/osboxes/anaconda3/envs/Py/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by CDM1619** [comment]
Hello，thanks for using this repository, you need to do the corresponding replacement for ENV and ALGO. Maybe you should try the following command, such as
python launcher.py --env 'catchup' --algo 'CPPO' --name ' ' --para '{}'，
python launcher.py --env 'slowdown' --algo 'DMPO' --name ' ' --para '{}'

I hope the above instructions can help you, thank you.

**Comment by TrinhTuanHung2021** [comment]
Thank you very much for your quick reply.
Now, I can run your models with the latest version of Sumo (1.14.1). I am not sure about the Flow environment you expressed in README.md. Maybe the Flow here https://flow.readthedocs.io/en/latest/flow_setup.html
I did not install Flow to run your models

**Comment by CDM1619** [comment]
After trainging, the actors model will be saved in checkpoints/standard _xxx/Models/xxxbest_actor.pt,
You just need to add :
self.actors.load_state_dict(torch.load(test_actors_model)) 
after initializing actors:
self.collect_pi, self.actors = self._init_actors()

test_actors_model = checkpoints/standard _xxx/Models/xxxbest_actor.pt

**Comment by TrinhTuanHung2021** [comment]
Thank you very much

**Comment by TrinhTuanHung2021** [comment]
Sorry for asking you.
There are some environments in your model, for example: eight, ring, catchup, slowdown, Grid, Monaco.
![image](https://user-images.githubusercontent.com/82990411/193268821-597f55ea-7310-4387-a3f9-6d89bd332b0c.png)
When I set env== Gird or Monaco, I can see the sumo file running as above
But with env= catchup or slowdown, the models run but I do not see anything. I do not understand these environments. Could you explain it to me? 
Thank you very much

**Comment by TrinhTuanHung2021** [comment]
I turned off GUI but I often got errors when training (env==Grid)
![image](https://user-images.githubusercontent.com/82990411/193274602-585412ec-aa79-47fc-a59f-a8187376e95c.png)

**Comment by CDM1619** [comment]
Hi，you can check our paper,  which has some introductions and references about eight, ring, catchup and slowdown，the four environments themselves have no visualization.
This error is not caused by the algorithm. It may be a problem with the running of the simulator in sumo. I did not meet a similar problem in version 1.11.0. I suggest you consider restarting the server or changing the sumo version to 1.11.0

**Comment by TrinhTuanHung2021** [comment]
Hello, I have built Sumo version 1.11.0 to train your model
I run your best model DMPO
`python launcher.py --env 'Grid' --algo 'DMPO'`
after 2 days of training, the simulation time is over 1 million seconds. I do not know when it finishes.
I tried to change parameters in  Model-Based-MARL/algorithms/config/ Grid_DMPO.py and Model-Based-MARL/algorithms/envs/NCS/config to reduce simulation steps but I can not. Could you show me how to define simulation steps?
And the result of the models is not good. The agents do not learn anything

**Comment by CDM1619** [comment]
Hello, If you want to reduce the simulation steps in every episode, maybe you can change the parameter “episode_length_sec’ in /algorithms/envs/NCS/config/config_ma2c_nc_grid.ini. If it doesn't work, it may be an internal property of the simulator, which I haven't studied in depth.

Because this environment is difficult and random, you may need a lot of experiments and a lot of parameter adjustments to get several better models. Actually, this environment is not our original, and we can hardly achieve the effect in this paper ‘’Multi-agent Reinforcement Learning For Networked System Control’’ through a lot of experiments. Maybe you can also try to save a better model at about 250k steps for testing in your figure, In short, this environment is more complex and requires a lot of experiments.

I am sorry that due to the limitation of the number of pages in the IROS conference, we can only show the most important information as much as possible. Please look forward to our full paper, which will also be published in the journal soon.

**Comment by TrinhTuanHung2021** [comment]
> ‘’Multi-agent Reinforcement Learning For Networked System Control

Thank you for your quick reply!
`episode_length_sec’` is only related to simulation time in each episode. I would like to change the total simulation time. For example, only training model in 200k.
I look forward to waiting for your new paper!

**Comment by CDM1619** [comment]
Thank you, you may change the ''alg_args.n_iter'' in /algorithms/config/ Grid_DMPO.py, which means how many epides you need, for example, in Grid, each episode length is 720, if you need to stop training at 200k steps, ''alg_args.n_iter'' needs to be set to 200k/720≈277.

**Comment by TrinhTuanHung2021** [comment]
Thank you but it does not right!
I set `alg_args.n_iter = 10`. According to you, the model will finish after training 7200s. But now, it is still running
 
![image](https://user-images.githubusercontent.com/82990411/199179695-78e10678-ce25-4e93-be02-9a585c4441e9.png)

**Comment by CDM1619** [comment]
Thank you for your reminding of this bug, maybe this parameter is overwritten. You can temporarily modify ’‘n_iter’‘ directly in main.py.
